export const SET_SETTINGS_FROM_STORAGE = 'SET_SETTINGS_FROM_STORAGE'
export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE'
export const UPDATE_BREAK_DURATION = 'UPDATE_BREAK_DURATION'
export const UPDATE_BREAK_FREQUENCY = 'UPDATE_BREAK_FREQUENCY'
export const UPDATE_DURATION = 'UPDATE_DURATION'
export const UPDATE_BREAK_TIME_LEFT = 'UPDATE_BREAK_TIME_LEFT'

export const UPDATE_TIME_LEFT = 'UPDATE_TIME_LEFT'
export const UPDATE_IS_RUNNING = 'UPDATE_IS_RUNNING'
export const UPDATE_REACHED_END = 'UPDATE_REACHED_END'
export const UPDATE_TIME_SINCE_BREAK = 'UPDATE_TIME_SINCE_BREAK'
export const UPDATE_IS_ON_BREAK = 'UPDATE_IS_ON_BREAK'

export const UPDATE_BREAK_DURATION_FROM_REMOTE =
  'UPDATE_BREAK_DURATION_FROM_REMOTE'
export const UPDATE_BREAK_FREQUENCY_FROM_REMOTE =
  'UPDATE_BREAK_FREQUENCY_FROM_REMOTE'
export const UPDATE_DURATION_FROM_REMOTE = 'UPDATE_DURATION_FROM_REMOTE'

export const UPDATE_IS_RUNNING_FROM_REMOTE = 'UPDATE_IS_RUNNING_FROM_REMOTE'
export const UPDATE_REACHED_END_FROM_REMOTE = 'UPDATE_REACHED_END_FROM_REMOTE'
export const UPDATE_IS_ON_BREAK_FROM_REMOTE = 'UPDATE_IS_ON_BREAK_FROM_REMOTE'

export const SET_TIME_IS_UP = 'SET_TIME_IS_UP'
export const SET_TIME_IS_UP_FROM_REMOTE = 'SET_TIME_IS_UP_FROM_REMOTE'

export const RESET_BREAK = 'RESET_BREAK'
export const RESET_BREAK_FROM_REMOTE = 'RESET_BREAK_FROM_REMOTE'
