export const SET_SETTINGS_FROM_STORAGE = 'SET_SETTINGS_FROM_STORAGE'
export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE'
export const UPDATE_BREAK_DURATION = 'UPDATE_BREAK_DURATION'
export const UPDATE_BREAK_FREQUENCY = 'UPDATE_BREAK_FREQUENCY'
export const UPDATE_DURATION = 'UPDATE_DURATION'
export const UPDATE_BREAK_TIME_LEFT = 'UPDATE_BREAK_TIME_LEFT'

export const UPDATE_BREAK_DURATION_FROM_REMOTE =
  'UPDATE_BREAK_DURATION_FROM_REMOTE'
export const UPDATE_BREAK_FREQUENCY_FROM_REMOTE =
  'UPDATE_BREAK_FREQUENCY_FROM_REMOTE'
export const UPDATE_DURATION_FROM_REMOTE = 'UPDATE_DURATION_FROM_REMOTE'
export const UPDATE_BREAK_TIME_LEFT_FROM_REMOTE =
  'UPDATE_BREAK_TIME_LEFT_FROM_REMOTE'
