export const ADD_ACTIVEUSER = 'ADD_ACTIVEUSER'
export const UPDATE_ACTIVEUSERS = 'UPDATE_ACTIVEUSERS'
export const UPDATE_INACTIVEUSERS = 'UPDATE_INACTIVEUSERS'
export const SET_FROM_STORAGE = 'SET_FROM_STORAGE'
